/**
 * Workflow Epoch identity (docs/plans/v1_hardening_decisions.md §4.1,
 * hardening plan GF-H09 / Phase 3).
 *
 * An epoch names ONE formal workflow round of an issue. It is generated by a
 * trusted runtime (the Gate, or the Driver when bootstrapping a
 * Producer-submitted issue) with a CSPRNG and persisted as a Gate-issued
 * record comment on the issue. It is NEVER derived from timestamps, comment
 * counts or labels; recovery always re-reads the records from GitHub.
 */
import { randomBytes } from 'node:crypto';

/** `wf_` + 12 lowercase base36 chars (~62 bits of entropy). */
const EPOCH_BODY_PATTERN = /^wf_[0-9a-z]{12}$/;

/** A well-formed workflow epoch string (nominal alias for readability). */
export type WorkflowEpoch = string;

/** True when `value` is a well-formed workflow epoch string. */
export function isWorkflowEpoch(value: unknown): value is WorkflowEpoch {
  return typeof value === 'string' && EPOCH_BODY_PATTERN.test(value);
}

/** Generate a fresh workflow epoch (`wf_` + 12 base36 chars). */
export function newWorkflowEpoch(): WorkflowEpoch {
  // 12 base36 chars from random bytes; rejection sampling keeps the
  // distribution uniform (252 = 7*36 is the largest multiple of 36 ≤ 255,
  // so bytes < 252 map onto 36 buckets without modulo bias).
  const alphabet = '0123456789abcdefghijklmnopqrstuvwxyz';
  let epoch = 'wf_';
  while (epoch.length < 3 + 12) {
    const bytes = randomBytes(16);
    for (const byte of bytes) {
      if (epoch.length >= 3 + 12) break;
      if (byte >= 252) continue;
      epoch += alphabet[byte % 36];
    }
  }
  return epoch;
}

/**
 * The epoch code embedded in dispatch ids: the epoch minus its `wf_` prefix
 * (base36 lowercase is filesystem-safe on Windows and POSIX).
 * Returns null for malformed epochs (callers fail closed).
 */
export function epochCode(epoch: string): string | null {
  if (!isWorkflowEpoch(epoch)) return null;
  return epoch.slice('wf_'.length);
}

/** Rebuilds the epoch from a dispatch-id epoch code (inverse of epochCode). */
export function epochFromCode(code: string): string | null {
  const epoch = `wf_${code}`;
  return isWorkflowEpoch(epoch) ? epoch : null;
}
